backend:
  name: git-gateway
  branch: master

media_folder: src/gallery
public_folder: /img

collections:
  - name: "testimonial"
    label: "Testimonial"
    folder: "content/testimonial"
    create: true
    identifier_field: author
    editor:
     preview: false
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "Year", name: "year", widget: "number", valueType: "int" }