backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    editor:
     preview: false
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Quote", name: "quote", widget: "string" }